services:
    elasticsearch:
        container_name: es01
        image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
        environment: 
            - 'ES_JAVA_OPTS=-Xms2g -Xmx2g'
            - 'bootstrap.memory_lock=true'
            - 'discovery.type=single-node'
            - 'xpack.security.enabled=false'
            - 'xpack.security.enrollment.enabled=false'
        ports:
            - 9200:9200
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536