services:
#    elasticsearch:
#        image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
#        environment:
#            - node.name=es01
#            - cluster.name=docker-cluster
#            - cluster.initial_master_nodes=es01
#            - bootstrap.memory_lock=true
#            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#        ulimits:
#            memlock:
#                soft: -1
#                hard: -1
#        ports:
#            - '9200:9200'
    
    elasticsearch:
        container_name: es01
        image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
        environment: 
            - 'ES_JAVA_OPTS=-Xms2g -Xmx2g'
            - 'bootstrap.memory_lock=true'
            - 'discovery.type=single-node'
            - 'xpack.security.enabled=false'
            - 'xpack.security.enrollment.enabled=false'
        ports:
            - 9200:9200
#        networks:
#            - elastic
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
          
#version: '3'
#services:
#    elasticsearch:
#        image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
#        environment:
#            - bootstrap.memory_lock=true
#            - discovery.type=single-node
#            - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
##            - ELASTIC_PASSWORD=password
##            - xpack.security.enabled=true
#        ulimits:
#            memlock:
#                soft: -1
#                hard: -1
#        ports:
#            - 9200:9200
#        networks: ['stack']